/*
UDC SQL D-15
INDEXES PARTITIONING AND QUERY OPTIMIZATION
*/

/* CHALLENGE: PRIVILEGES
1. CREATE THE USER mia WITH PASSWORD 'mia123'
2. CREATE THE ROLE analyst_emp
3. GRANT SELECT ON ALL TABLES IN THE PUBLIC SCHEMA TO THAT ROLE
4. GRANT INSERT AND UPDATE ON THE emoployees TABLE TO THAT ROLE
5. ADD THE PERMISSION TO CREATE DATABASES TO THAT ROLE.
6. ASSIGN THAT ROLE TO mia AND TEST THE PRIVILEGES WITH THAT USER
*/

-- 1.
CREATE USER mia
WITH PASSWORD 'mia123';

-- 2. 
CREATE ROLE analyst_emp;

-- 3. 
GRANT SELECT 
ON ALL TABLES IN SCHEMA public
TO analyst_emp;

-- 4. 
GRANT INSERT, UPDATE
ON employees
TO analyst_emp;

-- 5.
ALTER ROLE analyst_emp CREATEDB;

-- 6.
GRANT analyst_emp TO mia;



